#ifndef DATABASEPLUGIN_GLOBAL_H
#define DATABASEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEPLUGIN_LIBRARY)
#  define DATABASEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEPLUGIN_GLOBAL_H
